---
# Hadolint configuration for PrediGroweeV2-UI
# https://github.com/hadolint/hadolint

# Ignored rules
ignored:
  # DL3018: Pin versions in apk add - we intentionally use apk upgrade for latest security patches
  - DL3018

# Trusted registries for base images
trustedRegistries:
  - docker.io
